# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build
  displayName: 'dotnet build $(buildConfiguration)'

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Sid-demo-bstack'

- script: dotnet run Program.cs single
  displayName: 'dotnet run $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'logs.txt'
    publishLocation: 'pipeline'
